# VÆLORIA — bukkit.yml (extrait à fusionner).
# Moins de mobs naturels : le Faction vit des spawners, pas du spawn naturel.
spawn-limits:
  monsters: 50
  animals: 8
  water-animals: 3
  water-ambient: 3
  water-underground-creature: 3
  axolotls: 3
  ambient: 1
ticks-per:
  monster-spawns: 2
  animal-spawns: 400
  water-spawns: 400
  water-ambient-spawns: 400
  water-underground-creature-spawns: 400
  axolotl-spawns: 400
  ambient-spawns: 400
chunk-gc:
  period-in-ticks: 400
